### ISSUE TITLE
Bandpassfilter

### ISSUE THREAD

**Issue by kernel-panic-enjoyer** [skagmo/ngham#1]
Hi man,
somehow I was not able to find any other way to contact you, so im doing it here.
I was reading your post on your website (http://www.skagmo.com/page.php?p=projects/22_pihat), but the link you put in is down. Because im making a similar radio transmitter as an school projekt (https://github.com/ChristopheJacquet/PiFmRds) and for legal reasons I need to get a bandpass filter, but I can't find one in the Internet / I don't  really have a clue for what exactly I have to look for, I hope you can give me a direct link to and band pass filter shop.
And also, here in Germany the maximum transmitting power is 50nW, maybe you can even tell me which voltage divider I have to buy, I'd be really thankful!
Best regards

**Comment by skagmo** [comment]
Hi.

I assume you will transmit on a frequency within the tuning range of the 
synthesizer in the RPi.
You would not need a band pass filter then. You will only need a low 
pass filter to filter harmonics above the fundamental frequency.

Use a standard LC low pass filter with a cutoff frequency a little above 
the desired frequency. This can be found (among many other places) here:
http://www.filtro.net/products/filters/filters.asp

## 

Best regards
Jon Petter Skagmo

**Comment by kernel-panic-enjoyer** [comment]
But uhhh, in case that I have already bought one now (SAW FILTER, RF, 433.92MHZ MPN: B39431B3710U410 EPCOS), I could use this one, dont I? :smile:

**Comment by Vepox** [comment]
Hey man are you still here?: :o

**Comment by skagmo** [comment]
Hi. You can not use that filter, and you are doing something very different from PiHAT. In PiHAT, the synthesizer is tuned to a third of the desired frequency and the third harmonic is used by filtering with a band pass filter. A 433.92 MHz filter will only let through frequencies in that range, not frequencies within the FM broadcast band. You should get a low pass filter.
